---
title: "marchmadness2017"
output: html_document
---
 
```{r}
library(plyr)
library(dplyr)
library(stringr)
library(ggplot2)
 
inpath <- "C:/Users/Amy/Documents/GitHub/kaggle/marchmadness2017/"
 
#reg <- read.csv(paste0(inpath, "RegularSeasonCompactResults.csv"), stringsAsFactors = FALSE)
reg <- read.csv("C:/Users/cflagg/Documents/R_Projects/RegularSeasonCompactResults.csv", stringsAsFactors=FALSE)
#team <- read.csv(paste0(inpath, "Teams.csv"), stringsAsFactors = FALSE)
#seasons <- read.csv(paste0(inpath, "Seasons.csv"), stringsAsFactors = FALSE)
 
#tourney <- read.csv(paste0(inpath, "TourneyCompactResults.csv"), stringsAsFactors = FALSE)
 
head(reg)
 
```
 
```{r}
reg$wdiff <- reg$Wscore - reg$Lscore
reg$ldiff <- reg$Lscore - reg$Wscore
 
wreg <- select(reg, Season, Daynum, Wteam, Wscore, Wloc, Numot, wdiff) %>% rename(team=Wteam,score=Wscore,loc=Wloc,diff=wdiff)
lreg <- select(reg, Season, Daynum, Lteam, Lscore, Wloc, Numot, ldiff) %>% rename(team=Lteam,score=Lscore,loc=Wloc,diff=ldiff)
 
outreg <- rbind(wreg,lreg)
outreg$outcome <- ifelse(outreg$diff > 0, "win", "loss")

 
### NEED TO TURN OFF PLYR if dplyr:: is not specified for summarise
#detach(package:plyr)
start <- Sys.time()
proc_reg <- group_by(outreg, Season, team) %>%
  ## need to make sure to use summarise from dplyr, not plyr
  dplyr::summarise(totwin=sum(str_count(outcome, "win")),  # count total wins for the season
                   totloss=sum(str_count(outcome, "loss")),
                   ## average win margin - filter out negatives (those are losses), can do stdev too with same logic
                   wdiff_avg=mean(ifelse(diff>0, as.numeric(diff), 0)),
                   ldiff_avg=mean(ifelse(diff<0, as.numeric(diff), 0)),## average loss margin
                   score_avg=mean(score),
                   score_sd=sd(score),
                   wdiff_sd=sd(ifelse(diff>0, as.numeric(diff),0)),
                   ldiff_sd=sd(ifelse(diff<0, as.numeric(diff),0))
                   )
end <- Sys.time()
end - start # takes about 2.5 seconds to run
head(proc_reg)
```
```{r}
ggplot(proc_reg, aes(totwin,wdiff_avg)) + geom_point() + geom_smooth()
ggplot(proc_reg, aes(totwin,score_avg)) + geom_point()
ggplot(proc_reg, aes(totwin,wdiff_sd)) + geom_point()
```